

const acadiaAnimals = [
    "American black bear",
    "White-tailed deer",
    "Eastern coyote",
    "Red fox",
    "Snowshoe hare",
    "Moose",
    "Bobcat",
    "Fisher",
    "North American river otter",
    "American mink",
    "Striped skunk",
    "Porcupine",
    "Eastern gray squirrel",
    "Red squirrel",
    "American marten",
    "Meadow vole",
    "Woodchuck",
    "Northern raccoon",
    "Little brown bat",
    "Big brown bat",
    "Bald eagle",
    "Peregrine falcon",
    "Osprey",
    "Common loon",
    "Black-capped chickadee",
    "American robin",
    "Mourning dove",
    "Blue jay",
    "American crow",
    "Common raven",
    "Northern cardinal",
    "American goldfinch",
    "Song sparrow"
  ]

  const americanSamoaAnimals = [
    "Flying fox",
    "Pacific boa",
    "Coconut crab",
    "Giant centipede",
    "Crowned pigeon",
    "Purple-capped fruit dove",
    "Many-colored fruit dove",
    "Pacific imperial pigeon",
    "Zebra dove",
    "Red-vented bulbul",
    "Samoan starling",
    "Polynesian triller",
    "Samoan whistler",
    "Samoan flycatcher",
    "Samoan fantail",
    "Samoan moorhen",
    "Pacific reef heron",
    "Buff-banded rail",
    "Spotless crake",
    "Purple swamphen",
    "Pacific golden plover",
    "Wandering tattler",
    "Ruddy turnstone",
    "Bridled tern",
    "White tern",
    "Brown noddy",
    "Black noddy",
    "Red-footed booby",
    "Brown booby",
    "Masked booby",
    "Great frigatebird",
    "Lesser frigatebird"
  ]

  const archesAnimals = [
    "Desert bighorn sheep",
    "Mule deer",
    "Coyote",
    "Kit fox",
    "Black-tailed jackrabbit",
    "Desert cottontail",
    "Canyon mouse",
    "Deer mouse",
    "Northern grasshopper mouse",
    "Western harvest mouse",
    "Rock squirrel",
    "Round-tailed ground squirrel",
    "White-tailed antelope squirrel",
    "Striped skunk",
    "Ringtail",
    "Porcupine",
    "American badger",
    "Common raven",
    "Northern flicker",
    "Curve-billed thrasher",
    "Canyon wren",
    "Rock wren",
    "Northern mockingbird",
    "House finch",
    "Black-throated sparrow",
    "Common side-blotched lizard",
    "Greater short-horned lizard",
    "Desert spiny lizard",
    "Eastern fence lizard",
    "Sidewinder",
    "Gopher snake",
    "Great Basin rattlesnake",
    "Colorado River toad"
  ]

  const badlandsAnimals = [
    "American badger",
    "American bison",
    "Black-footed ferret",
    "Bighorn sheep",
    "Black-tailed prairie dog",
    "Coyote",
    "Deer mouse",
    "Eastern cottontail",
    "Feral hog",
    "Golden eagle",
    "Great horned owl",
    "Ground squirrel",
    "Kit fox",
    "Least weasel",
    "Long-tailed weasel",
    "Meadowlark",
    "Mule deer",
    "Northern grasshopper mouse",
    "Northern leopard frog",
    "Porcupine",
    "Prairie rattlesnake",
    "Pronghorn",
    "Red fox",
    "Red-tailed hawk",
    "Sharp-tailed grouse",
    "Silver-haired bat",
    "Swift fox",
    "Turkey vulture",
    "Western hognose snake",
    "Western meadowlark",
    "Western rattlesnake",
    "White-tailed deer",
    "Wild turkey"
  ]
  
  const bigBendAnimals = [
    "American black bear",
    "Coyote",
    "Bobcat",
    "Mountain lion",
    "Desert cottontail",
    "Black-tailed jackrabbit",
    "Rock squirrel",
    "Round-tailed ground squirrel",
    "Mexican ground squirrel",
    "Texas antelope squirrel",
    "Merriam's kangaroo rat",
    "Northern pygmy mouse",
    "White-throated woodrat",
    "Striped skunk",
    "Hooded skunk",
    "Ringtail",
    "Porcupine",
    "Nine-banded armadillo",
    "Greater roadrunner",
    "Curve-billed thrasher",
    "Verdin",
    "Northern mockingbird",
    "Curve-billed thrush",
    "Canyon towhee",
    "Common raven",
    "Greater earless lizard",
    "Texas horned lizard",
    "Common side-blotched lizard",
    "Greater short-horned lizard",
    "Desert spiny lizard",
    "Coachwhip",
    "Black-tailed rattlesnake",
    "Western diamondback rattlesnake"
  ]

  const biscayneAnimals = [
    "West Indian manatee",
    "Atlantic bottlenose dolphin",
    "Brown pelican",
    "Upside-down jellyfish",
    "Schaus swallowtail butterfly",
    "Loggerhead sea turtle",
    "Hawksbill sea turtle",
    "Green sea turtle",
    "Kemp's ridley sea turtle",
    "Leatherback sea turtle",
    "Least tern",
    "American crocodile",
    "Eastern indigo snake",
    "Smalltooth sawfish",
    "Pillar coral",
    "Elkhorn coral",
    "Staghorn coral",
    "Florida tree snail",
    "Miami blue butterfly",
    "Florida stone crab",
    "Spiny lobster",
    "Snapper",
    "Grouper",
    "Tarpon",
    "Bonefish",
    "Barracuda",
    "Great blue heron",
    "Tricolored heron",
    "Great egret",
    "Snowy egret",
    "Little blue heron",
    "Cattle egret"
  ]

  const blackCanyonAnimals = [
    "Mule deer",
    "Elk",
    "Mountain lion",
    "Bobcat",
    "Coyote",
    "Black bear",
    "Bighorn sheep",
    "Golden-mantled ground squirrel",
    "Least chipmunk",
    "Colorado chipmunk",
    "Yellow-bellied marmot",
    "White-tailed prairie dog",
    "Northern pocket gopher",
    "Deer mouse",
    "Meadow vole",
    "Western jumping mouse",
    "Striped skunk",
    "Long-tailed weasel",
    "American badger",
    "Northern flicker",
    "Downy woodpecker",
    "Hairy woodpecker",
    "White-breasted nuthatch",
    "Pygmy nuthatch",
    "Mountain chickadee",
    "Juniper titmouse",
    "American robin",
    "Spotted towhee",
    "Dark-eyed junco",
    "Broad-tailed hummingbird",
    "Common raven",
    "Northern leopard frog",
    "Woodhouse's toad"
  ]

  const bryceCanyonAnimals = [
    "Mule deer",
    "Pronghorn",
    "Coyote",
    "Bobcat",
    "Mountain lion",
    "Black bear",
    "Utah prairie dog",
    "Uinta chipmunk",
    "Golden-mantled ground squirrel",
    "Rock squirrel",
    "Deer mouse",
    "Northern grasshopper mouse",
    "Western harvest mouse",
    "Striped skunk",
    "Ringtail",
    "Porcupine",
    "Common raven",
    "Northern flicker",
    "Curve-billed thrasher",
    "Canyon wren",
    "Rock wren",
    "Northern mockingbird",
    "House finch",
    "Black-throated sparrow",
    "Common side-blotched lizard",
    "Greater short-horned lizard",
    "Desert spiny lizard",
    "Eastern fence lizard",
    "Sidewinder",
    "Gopher snake",
    "Great Basin rattlesnake",
    "Colorado River toad"
]

const canyonlandsAnimals = [
    "Desert bighorn sheep",
    "Mule deer",
    "Coyote",
    "Kit fox",
    "Black-tailed jackrabbit",
    "Desert cottontail",
    "Canyon mouse",
    "Deer mouse",
    "Northern grasshopper mouse",
    "Western harvest mouse",
    "Rock squirrel",
    "Round-tailed ground squirrel",
    "White-tailed antelope squirrel",
    "Striped skunk",
    "Ringtail",
    "Porcupine",
    "American badger",
    "Common raven",
    "Northern flicker",
    "Curve-billed thrasher",
    "Canyon wren",
    "Rock wren",
    "Northern mockingbird",
    "House finch",
    "Black-throated sparrow",
    "Common side-blotched lizard",
    "Greater short-horned lizard",
    "Desert spiny lizard",
    "Eastern fence lizard",
    "Sidewinder",
    "Gopher snake",
    "Great Basin rattlesnake",
    "Colorado River toad"
]

const capitolReefAnimals = [
    "Mule deer",
    "Pronghorn",
    "Coyote",
    "Bobcat",
    "Mountain lion",
    "Black bear",
    "Desert bighorn sheep",
    "Utah prairie dog",
    "Uinta chipmunk",
    "Golden-mantled ground squirrel",
    "Rock squirrel",
    "Deer mouse",
    "Northern grasshopper mouse",
    "Western harvest mouse",
    "Striped skunk",
    "Ringtail",
    "Porcupine",
    "Common raven",
    "Northern flicker",
    "Curve-billed thrasher",
    "Canyon wren",
    "Rock wren",
    "Northern mockingbird",
    "House finch",
    "Black-throated sparrow",
    "Common side-blotched lizard",
    "Greater short-horned lizard",
    "Desert spiny lizard",
    "Eastern fence lizard",
    "Sidewinder",
    "Gopher snake",
    "Great Basin rattlesnake",
    "Colorado River toad"
  ]

  const carlsbadCavernsAnimals = [
    "Mule deer",
    "Coyote",
    "Bobcat",
    "Mountain lion",
    "Black bear",
    "Javelina",
    "Ringtail",
    "Porcupine",
    "Striped skunk",
    "Cave myotis bat",
    "Brazilian free-tailed bat",
    "Townsend's big-eared bat",
    "Western pipistrelle bat",
    "Pallid bat",
    "Big brown bat",
    "Pocket gopher",
    "Deer mouse",
    "Northern grasshopper mouse",
    "Western harvest mouse",
    "Rock squirrel",
    "Round-tailed ground squirrel",
    "White-tailed antelope squirrel",
    "Common raven",
    "Northern flicker",
    "Curve-billed thrasher",
    "Canyon wren",
    "Rock wren",
    "Northern mockingbird",
    "House finch",
    "Black-throated sparrow",
    "Common side-blotched lizard",
    "Greater short-horned lizard",
    "Desert spiny lizard",
    "Eastern fence lizard",
    "Sidewinder",
    "Gopher snake",
    "Great Basin rattlesnake",
    "Colorado River toad"
  ]

  const channelIslandsAnimals = [
    "Island fox",
    "Steller sea lion",
    "California sea lion",
    "Harbor seal",
    "Northern elephant seal",
    "Pacific harbor porpoise",
    "Gray whale",
    "Humpback whale",
    "Blue whale",
    "Fin whale",
    "Orca",
    "Common dolphin",
    "Bottlenose dolphin",
    "California brown pelican",
    "Double-crested cormorant",
    "Brandt's cormorant",
    "Western gull",
    "Pigeon guillemot",
    "Cassin's auklet",
    "Ashy storm-petrel",
    "Black storm-petrel",
    "Scripps's murrelet",
    "Island scrub-jay",
    "Song sparrow",
    "Allen's hummingbird",
    "San Clemente loggerhead shrike",
    "San Clemente Bell's sparrow",
    "Island fence lizard",
    "Side-blotched lizard",
    "Western terrestrial garter snake",
    "Two-striped garter snake",
    "Island night lizard",
    "Channel Islands slender salamander",
    "Arroyo toad"
  ]

  const congareeAnimals = [
    "White-tailed deer",
    "Bobcats",
    "Wild pigs",
    "Foxes",
    "Opossums",
    "Deer",
    "River otters",
    "Red-Cockaded Woodpecker",
    "Red-shouldered hawks",
    "Wood ducks",
    "Barred owls",
    "Prothonotary warblers",
    "Pileated woodpeckers",
    "Northern parulas",
    "Swallow-tailed kites",
    "Eastern box turtles",
    "Five-lined skinks",
    "Northern water snakes",
    "Cottonmouths",
    "Copperheads",
    "Banded water snakes",
    "Eastern diamondback rattlesnakes",
    "Pine snakes",
    "Eastern mud turtles",
    "Eastern snapping turtles",
    "Spotted turtles",
    "Chicken turtles",
    "Eastern painted turtles",
    "River cooters",
    "Eastern musk turtles",
    "Striped mud turtles",
    "Eastern box turtles",
    "Common snapping turtles",
    "Eastern spiny softshells",
    "Spotted turtles"
]

const craterLakeAnimals = [
    "Black bear",
    "Coyote",
    "Bobcat",
    "Porcupine",
    "Yellow-bellied marmot",
    "Golden-mantled ground squirrel",
    "Douglas squirrel",
    "Deer mouse",
    "Northern flying squirrel",
    "Pacific jumping mouse",
    "Meadow vole",
    "Long-tailed vole",
    "Water shrew",
    "American pika",
    "Mazama pocket gopher",
    "Townsend's chipmunk",
    "Pacific marten",
    "Red fox",
    "Striped skunk",
    "Wolverine",
    "Northern flicker",
    "Hairy woodpecker",
    "White-headed woodpecker",
    "Stellar's jay",
    "Clark's nutcracker",
    "Dark-eyed junco",
    "Mountain chickadee",
    "Rufous hummingbird",
    "Common raven",
    "Northern alligator lizard",
    "Western fence lizard",
    "Rough-skinned newt",
    "Pacific chorus frog",
    "Western toad"
  ]

  const cuyahogaValleyAnimals = [
    "White-tailed deer",
    "Red fox",
    "Eastern gray squirrel",
    "Eastern chipmunk",
    "Woodchuck",
    "Eastern cottontail rabbit",
    "Northern raccoon",
    "Virginia opossum",
    "Striped skunk",
    "Long-tailed weasel",
    "American mink",
    "River otter",
    "Eastern mole",
    "White-footed mouse",
    "Meadow vole",
    "Eastern red bat",
    "Big brown bat",
    "Little brown bat",
    "Northern cardinal",
    "American robin",
    "Blue jay",
    "Mourning dove",
    "American crow",
    "Black-capped chickadee",
    "Tufted titmouse",
    "White-breasted nuthatch",
    "Downy woodpecker",
    "Hairy woodpecker",
    "Northern flicker",
    "American toad",
    "Fowler's toad",
    "Spring peeper",
    "Western chorus frog",
    "American bullfrog"
    ]

  const deathValleyAnimals = [
        "Desert bighorn sheep",
        "Coyote",
        "Bobcat",
        "Kit fox",
        "Black-tailed jackrabbit",
        "Antelope ground squirrel",
        "Round-tailed ground squirrel",
        "White-tailed antelope squirrel",
        "Kangaroo rat",
        "Desert pocket mouse",
        "Canyon mouse",
        "Deer mouse",
        "Northern grasshopper mouse",
        "Western harvest mouse",
        "Striped skunk",
        "Ringtail",
        "Porcupine",
        "Common raven",
        "Northern mockingbird",
        "Curve-billed thrasher",
        "Canyon wren",
        "Rock wren",
        "House finch",
        "Black-throated sparrow",
        "Common side-blotched lizard",
        "Greater short-horned lizard",
        "Desert spiny lizard",
        "Chuckwalla",
        "Sidewinder",
        "Gopher snake",
        "Great Basin rattlesnake",
        "Mojave rattlesnake",
        "Colorado River toad"
        ]

const denaliAnimals = [
            "Grizzly bear",
            "Black bear",
            "Dall sheep",
            "Caribou",
            "Moose",
            "Wolf",
            "Red fox",
            "Arctic ground squirrel",
            "Hoary marmot",
            "Red squirrel",
            "Snowshoe hare",
            "Porcupine",
            "River otter",
            "Bald eagle",
            "Golden eagle",
            "Peregrine falcon",
            "Rough-legged hawk",
            "Northern shrike",
            "Gray jay",
            "Willow ptarmigan",
            "Rock ptarmigan",
            "Spruce grouse",
            "Boreal chickadee",
            "American pipit",
            "Horned lark",
            "Mew gull",
            "Common raven",
            "Wood frog",
            "Spotted frog",
            "Tailed frog",
            "Willow toad",
            "Woodland vole"
]

const dryTortugasAnimals = [
    "Loggerhead sea turtle",
    "Hawksbill sea turtle",
    "Green sea turtle",
    "Kemp's ridley sea turtle",
    "Leatherback sea turtle",
    "Atlantic bottlenose dolphin",
    "West Indian manatee",
    "Great white shark",
    "Nurse shark",
    "Caribbean reef shark",
    "Goliath grouper",
    "Snapper",
    "Grouper",
    "Tarpon",
    "Bonefish",
    "Barracuda",
    "Great blue heron",
    "Tricolored heron",
    "Great egret",
    "Snowy egret",
    "Little blue heron",
    "Cattle egret",
    "Brown pelican",
    "Magnificent frigatebird",
    "Sooty tern",
    "Least tern",
    "Roseate tern",
    "Brown noddy",
    "Black noddy",
    "American crocodile",
    "Eastern indigo snake",
    "Pillar coral",
    "Elkhorn coral",
    "Staghorn coral"
  ]

  const evergladesAnimals = [
    "American alligator",
    "American crocodile",
    "Florida panther",
    "West Indian manatee",
    "North American river otter",
    "Bobcat",
    "Florida black bear",
    "White-tailed deer",
    "Marsh rabbit",
    "Raccoon",
    "Opossum",
    "Nine-banded armadillo",
    "Florida mink",
    "Striped skunk",
    "Florida red-bellied turtle",
    "Florida softshell turtle",
    "Florida snapping turtle",
    "American alligator snapping turtle",
    "Green anole",
    "Brown anole",
    "Northern curly-tailed lizard",
    "Florida worm lizard",
    "Eastern diamondback rattlesnake",
    "Dusky pygmy rattlesnake",
    "Florida cottonmouth",
    "Florida brown snake",
    "Florida kingsnake",
    "Florida pine snake",
    "Florida red-bellied snake",
    "Florida ribbon snake",
    "Florida water snake",
    "Florida green water snake",
    "Eastern indigo snake"
  ]
  const gatesOfTheArcticAnimals = [
    "Caribou",
    "Moose",
    "Wolf",
    "Grizzly bear",
    "Black bear",
    "Dall sheep",
    "Arctic ground squirrel",
    "Hoary marmot",
    "Red squirrel",
    "Snowshoe hare",
    "Porcupine",
    "River otter",
    "Bald eagle",
    "Golden eagle",
    "Peregrine falcon",
    "Rough-legged hawk",
    "Northern shrike",
    "Gray jay",
    "Willow ptarmigan",
    "Rock ptarmigan",
    "Spruce grouse",
    "Boreal chickadee",
    "American pipit",
    "Horned lark",
    "Mew gull",
    "Common raven",
    "Wood frog",
    "Spotted frog",
    "Tailed frog",
    "Willow toad",
    "Woodland vole"
  ];
  
  // Gateway Arch National Park animals
  const gatewayArchAnimals = [
    "Eastern gray squirrel",
    "Eastern chipmunk",
    "Eastern cottontail rabbit",
    "Northern raccoon",
    "Virginia opossum",
    "Striped skunk",
    "White-tailed deer",
    "Red fox",
    "Eastern mole",
    "White-footed mouse",
    "Meadow vole",
    "Eastern red bat",
    "Big brown bat",
    "Little brown bat",
    "Northern cardinal",
    "American robin",
    "Blue jay",
    "Mourning dove",
    "American crow",
    "Black-capped chickadee",
    "Tufted titmouse",
    "White-breasted nuthatch",
    "Downy woodpecker",
    "Hairy woodpecker",
    "Northern flicker",
    "American toad",
    "Fowler's toad",
    "Spring peeper",
    "Western chorus frog",
    "American bullfrog"
  ];

// Glacier National Park animals
const glacierNationalParkAnimals = [
    "Grizzly bear",
    "Black bear",
    "Mountain goat",
    "Bighorn sheep",
    "Elk",
    "Moose",
    "Mule deer",
    "White-tailed deer",
    "Cougar",
    "Bobcat",
    "Wolverine",
    "Wolf",
    "Coyote",
    "Red fox",
    "Marten",
    "Fisher",
    "River otter",
    "Bald eagle",
    "Golden eagle",
    "Osprey",
    "Peregrine falcon",
    "Merlin",
    "Northern goshawk",
    "Sharp-shinned hawk",
    "Cooper's hawk",
    "Red-tailed hawk",
    "Rough-legged hawk",
    "American kestrel",
    "Great horned owl",
    "Barred owl",
    "Northern pygmy owl",
    "Boreal owl",
    "Northern saw-whet owl"
  ];
  
  // Glacier Bay National Park animals
  const glacierBayNationalParkAnimals = [
    "Humpback whale",
    "Orca",
    "Dall's porpoise",
    "Harbor seal",
    "Steller sea lion",
    "Sea otter",
    "Black bear",
    "Brown bear",
    "Moose",
    "Mountain goat",
    "Wolf",
    "Coyote",
    "Red fox",
    "Marten",
    "River otter",
    "Bald eagle",
    "Golden eagle",
    "Osprey",
    "Peregrine falcon",
    "Merlin",
    "Northern goshawk",
    "Sharp-shinned hawk",
    "Cooper's hawk",
    "Red-tailed hawk",
    "Rough-legged hawk",
    "American kestrel",
    "Great horned owl",
    "Barred owl",
    "Northern pygmy owl",
    "Boreal owl",
    "Northern saw-whet owl"
  ];
  
  // Grand Canyon National Park animals
  const grandCanyonNationalParkAnimals = [
    "Mule deer",
    "Elk",
    "Mountain lion",
    "Bobcat",
    "Ringtail",
    "Kit fox",
    "Gray fox",
    "Coyote",
    "Badger",
    "Striped skunk",
    "Rock squirrel",
    "Golden-mantled ground squirrel",
    "Abert's squirrel",
    "Arizona gray squirrel",
    "California condor",
    "Common raven",
    "Northern flicker",
    "Curve-billed thrasher",
    "Canyon wren",
    "Rock wren",
    "Northern mockingbird",
    "House finch",
    "Black-throated sparrow",
    "Common side-blotched lizard",
    "Greater short-horned lizard",
    "Desert spiny lizard",
    "Chuckwalla",
    "Sidewinder",
    "Gopher snake",
    "Great Basin rattlesnake",
    "Mojave rattlesnake",
    "Colorado River toad"
  ];

// Grand Teton National Park animals
const grandTetonNationalParkAnimals = [
    "Moose",
    "Elk",
    "Mule deer",
    "Bison",
    "Bighorn sheep",
    "Grizzly bear",
    "Black bear",
    "Mountain lion",
    "Bobcat",
    "Coyote",
    "Red fox",
    "River otter",
    "Bald eagle",
    "Golden eagle",
    "Osprey",
    "Peregrine falcon",
    "Merlin",
    "Northern goshawk",
    "Sharp-shinned hawk",
    "Cooper's hawk",
    "Red-tailed hawk",
    "Rough-legged hawk",
    "American kestrel",
    "Great horned owl",
    "Barred owl",
    "Northern pygmy owl",
    "Boreal owl",
    "Northern saw-whet owl",
    "Common raven",
    "Clark's nutcracker",
    "Black-billed magpie",
    "American crow",
    "Mountain chickadee"
  ];
  
  // Great Basin National Park animals
  const greatBasinNationalParkAnimals = [
    "Pronghorn",
    "Mule deer",
    "Elk",
    "Mountain lion",
    "Bobcat",
    "Coyote",
    "Kit fox",
    "Gray fox",
    "Badger",
    "Striped skunk",
    "Yellow-bellied marmot",
    "Golden-mantled ground squirrel",
    "White-tailed antelope squirrel",
    "Pinyon jay",
    "Common raven",
    "Northern flicker",
    "Curve-billed thrasher",
    "Canyon wren",
    "Rock wren",
    "Northern mockingbird",
    "House finch",
    "Black-throated sparrow",
    "Common side-blotched lizard",
    "Greater short-horned lizard",
    "Desert spiny lizard",
    "Eastern fence lizard",
    "Sidewinder",
    "Gopher snake",
    "Great Basin rattlesnake",
    "Mojave rattlesnake",
    "Colorado River toad"
  ];
  
  // Great Sand Dunes National Park animals
  const greatSandDunesNationalParkAnimals = [
    "Mule deer",
    "Elk",
    "Mountain lion",
    "Bobcat",
    "Coyote",
    "Kit fox",
    "Gray fox",
    "Badger",
    "Striped skunk",
    "Rock squirrel",
    "Golden-mantled ground squirrel",
    "White-tailed antelope squirrel",
    "Pinyon jay",
    "Common raven",
    "Northern flicker",
    "Curve-billed thrasher",
    "Canyon wren",
    "Rock wren",
    "Northern mockingbird",
    "House finch",
    "Black-throated sparrow",
    "Common side-blotched lizard",
    "Greater short-horned lizard",
    "Desert spiny lizard",
    "Eastern fence lizard",
    "Sidewinder",
    "Gopher snake",
    "Great Basin rattlesnake",
    "Mojave rattlesnake",
    "Colorado River toad"
  ];

// Great Smoky Mountains National Park animals
const greatSmokyMountainsNationalParkAnimals = [
    "White-tailed deer",
    "Black bear",
    "Coyote",
    "Bobcat",
    "Red fox",
    "Gray fox",
    "Raccoon",
    "Opossum",
    "Eastern chipmunk",
    "Woodchuck",
    "Eastern cottontail rabbit",
    "Striped skunk",
    "Northern flying squirrel",
    "Southern flying squirrel",
    "Eastern gray squirrel",
    "American red squirrel",
    "Carolina northern flying squirrel",
    "Northern short-tailed shrew",
    "Least shrew",
    "Eastern mole",
    "Hairy-tailed mole",
    "Little brown bat",
    "Northern long-eared bat",
    "Indiana bat",
    "Eastern pipistrelle",
    "Big brown bat",
    "Eastern red bat",
    "Silver-haired bat",
    "Rafinesque's big-eared bat",
    "Seminole bat",
    "Eastern small-footed bat",
    "Northern myotis"
  ];
  
  // Guadalupe Mountains National Park animals
  const guadalupeMountainsNationalParkAnimals = [
    "Mule deer",
    "Elk",
    "Mountain lion",
    "Bobcat",
    "Coyote",
    "Kit fox",
    "Gray fox",
    "Badger",
    "Striped skunk",
    "Rock squirrel",
    "Golden-mantled ground squirrel",
    "White-tailed antelope squirrel",
    "Pinyon jay",
    "Common raven",
    "Northern flicker",
    "Curve-billed thrasher",
    "Canyon wren",
    "Rock wren",
    "Northern mockingbird",
    "House finch",
    "Black-throated sparrow",
    "Common side-blotched lizard",
    "Greater short-horned lizard",
    "Desert spiny lizard",
    "Eastern fence lizard",
    "Sidewinder",
    "Gopher snake",
    "Great Basin rattlesnake",
    "Mojave rattlesnake",
    "Colorado River toad"
  ];
  
  // Haleakala National Park animals
  const haleakalaNationalParkAnimals = [
    "Nene (Hawaiian goose)",
    "Hawaiian petrel",
    "Hawaiian hawk",
    "Hawaiian short-eared owl",
    "Hawaiian coot",
    "Hawaiian stilt",
    "Hawaiian moorhen",
    "Hawaiian duck",
    "Hawaiian thrush",
    "Apapane",
    "Iiwi",
    "Amakihi",
    "Hawaii creeper",
    "Hawaiian elepaio",
    "Omao",
    "Hawaii akepa",
    "Akohekohe",
    "Maui parrotbill",
    "Puaiohi",
    "Happy-face spider",
    "Wolf spider",
    "Garden orb weaver",
    "Spiny orb weaver",
    "Hawaiian garden centipede",
    "Kaulu (black-veiled chameleon)",
    "Gold dust day gecko",
    "Jackson's chameleon",
    "Common house gecko",
    "Mourning gecko",
    "Stump-toed gecko",
    "Green anole"
  ];

// Hawaii Volcanoes National Park animals
const hawaiiVolcanoesNationalParkAnimals = [
    "Nene (Hawaiian goose)",
    "Hawaiian petrel",
    "Hawaiian hawk",
    "Hawaiian short-eared owl",
    "Hawaiian coot",
    "Hawaiian stilt",
    "Hawaiian moorhen",
    "Hawaiian duck",
    "Hawaiian thrush",
    "Apapane",
    "Iiwi",
    "Amakihi",
    "Hawaii creeper",
    "Hawaiian elepaio",
    "Omao",
    "Hawaii akepa",
    "Akohekohe",
    "Maui parrotbill",
    "Puaiohi",
    "Happy-face spider",
    "Wolf spider",
    "Garden orb weaver",
    "Spiny orb weaver",
    "Hawaiian garden centipede",
    "Kaulu (black-veiled chameleon)",
    "Gold dust day gecko",
    "Jackson's chameleon",
    "Common house gecko",
    "Mourning gecko",
    "Stump-toed gecko",
    "Green anole"
  ];
  
  // Hot Springs National Park animals
  const hotSpringsNationalParkAnimals = [
    "White-tailed deer",
    "Eastern gray squirrel",
    "Eastern chipmunk",
    "Eastern cottontail rabbit",
    "Northern raccoon",
    "Virginia opossum",
    "Striped skunk",
    "Red fox",
    "Eastern mole",
    "White-footed mouse",
    "Meadow vole",
    "Eastern red bat",
    "Big brown bat",
    "Little brown bat",
    "Northern cardinal",
    "American robin",
    "Blue jay",
    "Mourning dove",
    "American crow",
    "Black-capped chickadee",
    "Tufted titmouse",
    "White-breasted nuthatch",
    "Downy woodpecker",
    "Hairy woodpecker",
    "Northern flicker",
    "American toad",
    "Fowler's toad",
    "Spring peeper",
    "Western chorus frog",
    "American bullfrog"
  ];
  
  // Indiana Dunes National Park animals
  const indianaDunesNationalParkAnimals = [
    "White-tailed deer",
    "Eastern gray squirrel",
    "Eastern chipmunk",
    "Eastern cottontail rabbit",
    "Northern raccoon",
    "Virginia opossum",
    "Striped skunk",
    "Red fox",
    "Eastern mole",
    "White-footed mouse",
    "Meadow vole",
    "Eastern red bat",
    "Big brown bat",
    "Little brown bat",
    "Northern cardinal",
    "American robin",
    "Blue jay",
    "Mourning dove",
    "American crow",
    "Black-capped chickadee",
    "Tufted titmouse",
    "White-breasted nuthatch",
    "Downy woodpecker",
    "Hairy woodpecker",
    "Northern flicker",
    "American toad",
    "Fowler's toad",
    "Spring peeper",
    "Western chorus frog",
    "American bullfrog"
  ];

// Isle Royale National Park animals
const isleRoyaleNationalParkAnimals = [
    "Moose",
    "Wolf",
    "Snowshoe hare",
    "Red squirrel",
    "American marten",
    "Beaver",
    "River otter",
    "Bald eagle",
    "Peregrine falcon",
    "Osprey",
    "Common raven",
    "Black-billed magpie",
    "Blue jay",
    "American crow",
    "Common raven",
    "Boreal chickadee",
    "Red-breasted nuthatch",
    "Winter wren",
    "Golden-crowned kinglet",
    "American robin",
    "Yellow-rumped warbler",
    "White-throated sparrow",
    "Dark-eyed junco",
    "Wood frog",
    "Spring peeper",
    "Chorus frog",
    "Gray treefrog",
    "Mink frog",
    "Green frog",
    "Pickerel frog",
    "Northern leopard frog",
    "American toad"
];

// Joshua Tree National Park animals
const joshuaTreeNationalParkAnimals = [
    "Desert bighorn sheep",
    "Coyote",
    "Bobcat",
    "Kit fox",
    "Black-tailed jackrabbit",
    "Antelope ground squirrel",
    "Round-tailed ground squirrel",
    "White-tailed antelope squirrel",
    "Kangaroo rat",
    "Desert pocket mouse",
    "Canyon mouse",
    "Deer mouse",
    "Northern grasshopper mouse",
    "Western harvest mouse",
    "Striped skunk",
    "Ringtail",
    "Porcupine",
    "Common raven",
    "Northern mockingbird",
    "Curve-billed thrasher",
    "Canyon wren",
    "Rock wren",
    "House finch",
    "Black-throated sparrow",
    "Common side-blotched lizard",
    "Greater short-horned lizard",
    "Desert spiny lizard",
    "Chuckwalla",
    "Sidewinder",
    "Gopher snake",
    "Great Basin rattlesnake",
    "Mojave rattlesnake",
    "Colorado River toad"
];

// Katmai National Park animals
const katmaiNationalParkAnimals = [
    "Brown bear",
    "Moose",
    "Caribou",
    "Wolf",
    "Red fox",
    "River otter",
    "Bald eagle",
    "Golden eagle",
    "Osprey",
    "Peregrine falcon",
    "Merlin",
    "Northern goshawk",
    "Sharp-shinned hawk",
    "Cooper's hawk",
    "Red-tailed hawk",
    "Rough-legged hawk",
    "American kestrel",
    "Great horned owl",
    "Barred owl",
    "Northern pygmy owl",
    "Boreal owl",
    "Northern saw-whet owl",
    "Common raven",
    "Clark's nutcracker",
    "Black-billed magpie",
    "American crow",
    "Mountain chickadee",
    "Boreal chickadee",
    "Red-breasted nuthatch",
    "Winter wren",
    "Golden-crowned kinglet"
];

// Kenai Fjords National Park animals
const kenaiFjordsNationalParkAnimals = [
    "Humpback whale",
    "Orca (killer whale)",
    "Dall's porpoise",
    "Harbor seal",
    "Steller sea lion",
    "Sea otter",
    "Bald eagle",
    "Golden eagle",
    "Osprey",
    "Peregrine falcon",
    "Merlin",
    "Northern goshawk",
    "Sharp-shinned hawk",
    "Cooper's hawk",
    "Red-tailed hawk",
    "Rough-legged hawk",
    "American kestrel",
    "Great horned owl",
    "Barred owl",
    "Northern pygmy owl",
    "Boreal owl",
    "Northern saw-whet owl",
    "Common raven",
    "Clark's nutcracker",
    "Black-billed magpie",
    "American crow",
    "Mountain chickadee",
    "Boreal chickadee",
    "Red-breasted nuthatch",
    "Winter wren",
    "Golden-crowned kinglet",
    "Harbor seal"
];

// Kings Canyon National Park animals
const kingsCanyonNationalParkAnimals = [
    "Mule deer",
    "Black bear",
    "Coyote",
    "Bobcat",
    "Mountain lion",
    "Gray fox",
    "Ringtail",
    "Striped skunk",
    "American badger",
    "Yellow-bellied marmot",
    "Golden-mantled ground squirrel",
    "California ground squirrel",
    "Least chipmunk",
    "Long-eared chipmunk",
    "Douglas squirrel",
    "Western gray squirrel",
    "Pygmy nuthatch",
    "White-breasted nuthatch",
    "Brown creeper",
    "Bewick's wren",
    "House wren",
    "Pacific wren",
    "Western bluebird",
    "Steller's jay",
    "California scrub jay",
    "Common raven",
    "American robin",
    "Dark-eyed junco",
    "Yellow-rumped warbler",
    "Western tanager",
    "Black-headed grosbeak"
];

// Kobuk Valley National Park animals
const kobukValleyNationalParkAnimals = [
    "Caribou",
    "Muskox",
    "Wolf",
    "Red fox",
    "Arctic fox",
    "Wolverine",
    "Lynx",
    "River otter",
    "Bald eagle",
    "Golden eagle",
    "Osprey",
    "Peregrine falcon",
    "Merlin",
    "Northern goshawk",
    "Sharp-shinned hawk",
    "Cooper's hawk",
    "Red-tailed hawk",
    "Rough-legged hawk",
    "American kestrel",
    "Great horned owl",
    "Barred owl",
    "Northern pygmy owl",
    "Boreal owl",
    "Northern saw-whet owl",
    "Common raven",
    "Clark's nutcracker",
    "Black-billed magpie",
    "American crow",
    "Mountain chickadee",
    "Boreal chickadee",
    "Red-breasted nuthatch",
    "Winter wren",
    "Golden-crowned kinglet"
];

// Lake Clark National Park animals
const lakeClarkNationalParkAnimals = [
    "Moose",
    "Caribou",
    "Brown bear",
    "Black bear",
    "Wolf",
    "Red fox",
    "River otter",
    "Bald eagle",
    "Golden eagle",
    "Osprey",
    "Peregrine falcon",
    "Merlin",
    "Northern goshawk",
    "Sharp-shinned hawk",
    "Cooper's hawk",
    "Red-tailed hawk",
    "Rough-legged hawk",
    "American kestrel",
    "Great horned owl",
    "Barred owl",
    "Northern pygmy owl",
    "Boreal owl",
    "Northern saw-whet owl",
    "Common raven",
    "Clark's nutcracker",
    "Black-billed magpie",
    "American crow",
    "Mountain chickadee",
    "Boreal chickadee",
    "Red-breasted nuthatch",
    "Winter wren",
    "Golden-crowned kinglet"
  ];
  
  // Lassen Volcanic National Park animals
  const lassenVolcanicNationalParkAnimals = [
    "Mule deer",
    "Black bear",
    "Coyote",
    "Bobcat",
    "Mountain lion",
    "Gray fox",
    "Ringtail",
    "Striped skunk",
    "American badger",
    "Yellow-bellied marmot",
    "Golden-mantled ground squirrel",
    "California ground squirrel",
    "Least chipmunk",
    "Long-eared chipmunk",
    "Douglas squirrel",
    "Western gray squirrel",
    "Pygmy nuthatch",
    "White-breasted nuthatch",
    "Brown creeper",
    "Bewick's wren",
    "House wren",
    "Pacific wren",
    "Western bluebird",
    "Steller's jay",
    "California scrub jay",
    "Common raven",
    "American robin",
    "Dark-eyed junco",
    "Yellow-rumped warbler",
    "Western tanager",
    "Black-headed grosbeak"
  ];
  
  // Mammoth Cave National Park animals
  const mammothCaveNationalParkAnimals = [
    "White-tailed deer",
    "Eastern gray squirrel",
    "Eastern chipmunk",
    "Eastern cottontail rabbit",
    "Northern raccoon",
    "Virginia opossum",
    "Striped skunk",
    "Red fox",
    "Eastern mole",
    "White-footed mouse",
    "Meadow vole",
    "Eastern red bat",
    "Big brown bat",
    "Little brown bat",
    "Northern cardinal",
    "American robin",
    "Blue jay",
    "Mourning dove",
    "American crow",
    "Black-capped chickadee",
    "Tufted titmouse",
    "White-breasted nuthatch",
    "Downy woodpecker",
    "Hairy woodpecker",
    "Northern flicker",
    "American toad",
    "Fowler's toad",
    "Spring peeper",
    "Western chorus frog",
    "American bullfrog"
  ];

// Mesa Verde National Park animals
const mesaVerdeNationalParkAnimals = [
    "Mule deer",
    "Elk",
    "Black bear",
    "Coyote",
    "Bobcat",
    "Mountain lion",
    "Gray fox",
    "Striped skunk",
    "Ringtail",
    "American badger",
    "Rock squirrel",
    "Golden-mantled ground squirrel",
    "White-tailed antelope squirrel",
    "Pinyon jay",
    "Common raven",
    "Northern flicker",
    "Curve-billed thrasher",
    "Canyon wren",
    "Rock wren",
    "Northern mockingbird",
    "House finch",
    "Black-throated sparrow",
    "Common side-blotched lizard",
    "Greater short-horned lizard",
    "Desert spiny lizard",
    "Eastern fence lizard",
    "Sidewinder",
    "Gopher snake",
    "Great Basin rattlesnake",
    "Mojave rattlesnake",
    "Colorado River toad"
  ];
  
  // Mount Rainier National Park animals
  const mountRainierNationalParkAnimals = [
    "Black bear",
    "Coyote",
    "Bobcat",
    "Mountain lion",
    "Cascade red fox",
    "Fisher",
    "Raccoon",
    "Mink",
    "Striped skunk",
    "Short-tailed weasel",
    "Long-tailed weasel",
    "Marten",
    "Wolverine",
    "Northern spotted owl",
    "Bald eagle",
    "Golden eagle",
    "Peregrine falcon",
    "Merlin",
    "Northern goshawk",
    "Sharp-shinned hawk",
    "Cooper's hawk",
    "Red-tailed hawk",
    "Rough-legged hawk",
    "American kestrel",
    "Great horned owl",
    "Barred owl",
    "Northern pygmy owl",
    "Boreal owl",
    "Northern saw-whet owl",
    "Common raven",
    "Clark's nutcracker",
    "Black-billed magpie",
    "American crow"
  ];
  
  // New River Gorge National Park animals
  const newRiverGorgeNationalParkAnimals = [
    "White-tailed deer",
    "Black bear",
    "Coyote",
    "Bobcat",
    "Red fox",
    "Gray fox",
    "Raccoon",
    "Opossum",
    "Eastern chipmunk",
    "Woodchuck",
    "Eastern cottontail rabbit",
    "Striped skunk",
    "Northern flying squirrel",
    "Southern flying squirrel",
    "Eastern gray squirrel",
    "American red squirrel",
    "Carolina northern flying squirrel",
    "Northern short-tailed shrew",
    "Least shrew",
    "Eastern mole",
    "Hairy-tailed mole",
    "Little brown bat",
    "Northern long-eared bat",
    "Indiana bat",
    "Eastern pipistrelle",
    "Big brown bat",
    "Eastern red bat",
    "Silver-haired bat",
    "Rafinesque's big-eared bat",
    "Seminole bat",
    "Eastern small-footed bat",
    "Northern myotis"
  ];

// North Cascades National Park animals
const northCascadesNationalParkAnimals = [
    "Black bear",
    "Cougar",
    "Bobcat",
    "Coyote",
    "Red fox",
    "Marten",
    "Fisher",
    "Mink",
    "Wolverine",
    "Lynx",
    "Striped skunk",
    "Raccoon",
    "River otter",
    "Porcupine",
    "Townsend's chipmunk",
    "Douglas squirrel",
    "Beaver",
    "American pika",
    "Columbian black-tailed deer",
    "Mountain goat",
    "Moose",
    "Gray wolf",
    "Bald eagle",
    "Golden eagle",
    "Peregrine falcon",
    "Merlin",
    "Northern goshawk",
    "Sharp-shinned hawk",
    "Cooper's hawk",
    "Red-tailed hawk",
    "Rough-legged hawk",
    "American kestrel",
    "Great horned owl",
    "Barred owl"
  ];
  
  // Olympic National Park animals
  const olympicNationalParkAnimals = [
    "Roosevelt elk",
    "Black bear",
    "Cougar",
    "Bobcat",
    "Coyote",
    "Red fox",
    "Marten",
    "Fisher",
    "Mink",
    "Striped skunk",
    "Raccoon",
    "River otter",
    "Porcupine",
    "Townsend's chipmunk",
    "Douglas squirrel",
    "Beaver",
    "Northern spotted owl",
    "Bald eagle",
    "Golden eagle",
    "Peregrine falcon",
    "Merlin",
    "Northern goshawk",
    "Sharp-shinned hawk",
    "Cooper's hawk",
    "Red-tailed hawk",
    "Rough-legged hawk",
    "American kestrel",
    "Great horned owl",
    "Barred owl",
    "Northern pygmy owl",
    "Boreal owl",
    "Northern saw-whet owl",
    "Common raven",
    "Clark's nutcracker"
  ];
  
  // Petrified Forest National Park animals
  const petrifiedForestNationalParkAnimals = [
    "Black-tailed jackrabbit",
    "Desert cottontail",
    "Round-tailed ground squirrel",
    "Rock squirrel",
    "White-throated woodrat",
    "Deer mouse",
    "Northern grasshopper mouse",
    "Western harvest mouse",
    "Canyon mouse",
    "Apache pocket mouse",
    "Silky pocket mouse",
    "Hispid pocket mouse",
    "Rock pocket mouse",
    "Merriam's kangaroo rat",
    "Ord's kangaroo rat",
    "Banner-tailed kangaroo rat",
    "Coyote",
    "Bobcat",
    "Kit fox",
    "Striped skunk",
    "Ringtail",
    "Porcupine",
    "Common raven",
    "Northern mockingbird",
    "Curve-billed thrasher",
    "Canyon wren",
    "Rock wren",
    "House finch",
    "Black-throated sparrow",
    "Common side-blotched lizard",
    "Greater short-horned lizard",
    "Desert spiny lizard",
    "Chuckwalla",
    "Sidewinder",
    "Gopher snake",
    "Great Basin rattlesnake",
    "Mojave rattlesnake",
    "Colorado River toad"
  ];

// Pinnacles National Park animals
const pinnaclesNationalParkAnimals = [
    "California condor",
    "Pronghorn",
    "Black bear",
    "Coyote",
    "Bobcat",
    "Mountain lion",
    "Gray fox",
    "Striped skunk",
    "Ringtail",
    "American badger",
    "California ground squirrel",
    "Antelope ground squirrel",
    "Bewick's wren",
    "House wren",
    "Pacific wren",
    "Western bluebird",
    "Steller's jay",
    "California scrub jay",
    "Common raven",
    "American robin",
    "Dark-eyed junco",
    "Yellow-rumped warbler",
    "Western tanager",
    "Black-headed grosbeak",
    "Common side-blotched lizard",
    "Greater short-horned lizard",
    "Desert spiny lizard",
    "Western fence lizard",
    "Sidewinder",
    "Gopher snake",
    "Great Basin rattlesnake",
    "Mojave rattlesnake",
    "Colorado River toad",
    "Western toad"
  ];
  
  // Redwood National Park animals
  const redwoodNationalParkAnimals = [
    "Roosevelt elk",
    "Black bear",
    "Cougar",
    "Bobcat",
    "Coyote",
    "Red fox",
    "Marten",
    "Fisher",
    "Mink",
    "Striped skunk",
    "Raccoon",
    "River otter",
    "Porcupine",
    "Townsend's chipmunk",
    "Douglas squirrel",
    "Beaver",
    "Northern spotted owl",
    "Bald eagle",
    "Golden eagle",
    "Peregrine falcon",
    "Merlin",
    "Northern goshawk",
    "Sharp-shinned hawk",
    "Cooper's hawk",
    "Red-tailed hawk",
    "Rough-legged hawk",
    "American kestrel",
    "Great horned owl",
    "Barred owl",
    "Northern pygmy owl",
    "Boreal owl",
    "Northern saw-whet owl",
    "Common raven",
    "Clark's nutcracker"
  ];
  
  // Rocky Mountain National Park animals
  const rockyMountainNationalParkAnimals = [
    "Elk",
    "Mule deer",
    "Bighorn sheep",
    "Mountain goat",
    "Black bear",
    "Coyote",
    "Bobcat",
    "Marten",
    "Fisher",
    "Wolverine",
    "Lynx",
    "Striped skunk",
    "Raccoon",
    "River otter",
    "Porcupine",
    "Golden-mantled ground squirrel",
    "Least chipmunk",
    "Yellow-bellied marmot",
    "American pika",
    "Northern pocket gopher",
    "Meadow vole",
    "Montane vole",
    "Long-tailed vole",
    "Southern red-backed vole",
    "Meadow jumping mouse",
    "Western jumping mouse",
    "Deer mouse",
    "Northern grasshopper mouse",
    "Western harvest mouse",
    "Colorado chipmunk",
    "Wyoming ground squirrel",
    "American marten",
    "Beaver",
    "Northern river otter"
  ];
  
// Saguaro National Park animals
const saguaroNationalParkAnimals = [
    "Coyote",
    "Bobcat",
    "Mountain lion",
    "Kit fox",
    "Ringtail",
    "Striped skunk",
    "Gila monster",
    "Desert tortoise",
    "Chuckwalla",
    "Desert spiny lizard",
    "Gopher snake",
    "Common raven",
    "Northern mockingbird",
    "Curve-billed thrasher",
    "Canyon wren",
    "Rock wren",
    "House finch",
    "Black-throated sparrow",
    "Greater roadrunner",
    "Costa's hummingbird",
    "Anna's hummingbird",
    "Black-chinned hummingbird",
    "Elf owl",
    "Burrowing owl",
    "Greater earless lizard",
    "Desert iguana",
    "Regal horned lizard",
    "Coachwhip",
    "Rosy boa",
    "Western diamondback rattlesnake",
    "Black-tailed rattlesnake",
    "Tiger rattlesnake",
    "Arizona coral snake",
    "Desert kingsnake",
    "Sonoran mountain kingsnake"
  ];
  
  // Sequoia National Park animals
  const sequoiaNationalParkAnimals = [
    "Mule deer",
    "Black bear",
    "Coyote",
    "Bobcat",
    "Mountain lion",
    "Gray fox",
    "Ringtail",
    "Striped skunk",
    "American badger",
    "Yellow-bellied marmot",
    "Golden-mantled ground squirrel",
    "California ground squirrel",
    "Least chipmunk",
    "Long-eared chipmunk",
    "Douglas squirrel",
    "Western gray squirrel",
    "Pygmy nuthatch",
    "White-breasted nuthatch",
    "Brown creeper",
    "Bewick's wren",
    "House wren",
    "Pacific wren",
    "Western bluebird",
    "Steller's jay",
    "California scrub jay",
    "Common raven",
    "American robin",
    "Dark-eyed junco",
    "Yellow-rumped warbler",
    "Western tanager",
    "Black-headed grosbeak",
    "Wrentit",
    "California thrasher",
    "Olive-sided flycatcher"
  ];
  
  // Shenandoah National Park animals
  const shenandoahNationalParkAnimals = [
    "White-tailed deer",
    "Black bear",
    "Bobcat",
    "Coyote",
    "Red fox",
    "Gray fox",
    "Raccoon",
    "Opossum",
    "Eastern chipmunk",
    "Woodchuck",
    "Eastern cottontail rabbit",
    "Striped skunk",
    "Northern flying squirrel",
    "Southern flying squirrel",
    "Eastern gray squirrel",
    "American red squirrel",
    "Carolina northern flying squirrel",
    "Northern short-tailed shrew",
    "Least shrew",
    "Eastern mole",
    "Hairy-tailed mole",
    "Little brown bat",
    "Northern long-eared bat",
    "Indiana bat",
    "Eastern pipistrelle",
    "Big brown bat",
    "Eastern red bat",
    "Silver-haired bat",
    "Rafinesque's big-eared bat",
    "Seminole bat",
    "Eastern small-footed bat",
    "Northern myotis"
  ];
  
  const theodoreRooseveltNationalParkAnimals = [
    "Bison",
    "Elk",
    "Mule deer",
    "White-tailed deer",
    "Pronghorn",
    "Bighorn sheep",
    "Black-tailed prairie dog",
    "Black-footed ferret",
    "Coyote",
    "Swift fox",
    "Bobcat",
    "Mountain lion",
    "Badger",
    "Striped skunk",
    "Raccoon",
    "River otter",
    "Porcupine",
    "Black-tailed jackrabbit",
    "White-tailed jackrabbit",
    "Eastern cottontail",
    "White-tailed prairie dog",
    "Black-tailed prairie dog",
    "Northern grasshopper mouse",
    "Meadow vole",
    "Montane vole",
    "Meadow jumping mouse",
    "Western jumping mouse",
    "Deer mouse",
    "Northern pocket gopher",
    "Plains pocket gopher",
    "Black-tailed prairie dog",
    "White-tailed prairie dog",
    "American badger",
    "American marten",
    "Beaver",
    "Northern river otter"
  ];

  const virginIslandsNationalParkAnimals = [
    "Hawksbill sea turtle",
    "Green sea turtle",
    "Leatherback sea turtle",
    "Loggerhead sea turtle",
    "Spotted eagle ray",
    "Manta ray",
    "Bottlenose dolphin",
    "Humpback whale",
    "Short-beaked common dolphin",
    "Spinner dolphin",
    "Pantropical spotted dolphin",
    "Rough-toothed dolphin",
    "Atlantic spotted dolphin",
    "Frigatebird",
    "Brown pelican",
    "Red-footed booby",
    "Masked booby",
    "Brown booby",
    "Magnificent frigatebird",
    "Great frigatebird",
    "Brown noddy",
    "Black noddy",
    "Sooty tern",
    "Bridled tern",
    "Roseate tern",
    "Least tern",
    "Laughing gull",
    "Royal tern",
    "Sanderling",
    "Semipalmated plover",
    "Wilson's plover",
    "Willet",
    "Ruddy turnstone",
    "Spotted sandpiper",
    "Whimbrel"
  ];

  const voyageursNationalParkAnimals = [
    "Moose",
    "White-tailed deer",
    "Black bear",
    "Gray wolf",
    "Canada lynx",
    "Bobcat",
    "Coyote",
    "Red fox",
    "River otter",
    "Beaver",
    "American marten",
    "Fisher",
    "Mink",
    "Striped skunk",
    "Raccoon",
    "Porcupine",
    "Northern flying squirrel",
    "Southern flying squirrel",
    "Eastern gray squirrel",
    "American red squirrel",
    "Meadow vole",
    "Montane vole",
    "Southern red-backed vole",
    "Meadow jumping mouse",
    "Western jumping mouse",
    "Deer mouse",
    "Northern bog lemming",
    "Southern bog lemming",
    "Muskrat",
    "North American beaver",
    "American mink",
    "American marten",
    "Fisher",
    "River otter"
  ];

  const whiteSandsNationalParkAnimals = [
    "Coyote",
    "Kit fox",
    "Badger",
    "Bobcats",
    "Ringtail",
    "Striped skunk",
    "Gila monster",
    "Desert tortoise",
    "Chuckwalla",
    "Desert spiny lizard",
    "Gopher snake",
    "Common raven",
    "Northern mockingbird",
    "Curve-billed thrasher",
    "Canyon wren",
    "Rock wren",
    "House finch",
    "Black-throated sparrow",
    "Greater roadrunner",
    "Costa's hummingbird",
    "Anna's hummingbird",
    "Black-chinned hummingbird",
    "Elf owl",
    "Burrowing owl",
    "Greater earless lizard",
    "Desert iguana",
    "Regal horned lizard",
    "Coachwhip",
    "Rosy boa",
    "Western diamondback rattlesnake",
    "Black-tailed rattlesnake",
    "Tiger rattlesnake",
    "Arizona coral snake",
    "Desert kingsnake",
    "Sonoran mountain kingsnake"
  ];

  const windCaveNationalParkAnimals = [
    "Bison",
    "Elk",
    "Mule deer",
    "White-tailed deer",
    "Pronghorn",
    "Bighorn sheep",
    "Black-tailed prairie dog",
    "Black-footed ferret",
    "Coyote",
    "Swift fox",
    "Bobcat",
    "Mountain lion",
    "Badger",
    "Striped skunk",
    "Raccoon",
    "River otter",
    "Porcupine",
    "Black-tailed jackrabbit",
    "White-tailed jackrabbit",
    "Eastern cottontail",
    "White-tailed prairie dog",
    "Black-tailed prairie dog",
    "Northern grasshopper mouse",
    "Meadow vole",
    "Montane vole",
    "Meadow jumping mouse",
    "Western jumping mouse",
    "Deer mouse",
    "Northern pocket gopher",
    "Plains pocket gopher",
    "Black-tailed prairie dog",
    "White-tailed prairie dog",
    "American badger",
    "American marten",
    "Beaver",
    "Northern river otter"
  ];

  const wrangellStEliasNationalParkAnimals = [
    "Moose",
    "Dall sheep",
    "Mountain goat",
    "Caribou",
    "Brown bear",
    "Black bear",
    "Gray wolf",
    "Canada lynx",
    "Bobcat",
    "Coyote",
    "Red fox",
    "River otter",
    "Beaver",
    "American marten",
    "Fisher",
    "Mink",
    "Striped skunk",
    "Raccoon",
    "Porcupine",
    "Northern flying squirrel",
    "Southern flying squirrel",
    "Eastern gray squirrel",
    "American red squirrel",
    "Meadow vole",
    "Montane vole",
    "Southern red-backed vole",
    "Meadow jumping mouse",
    "Western jumping mouse",
    "Deer mouse",
    "Northern bog lemming",
    "Southern bog lemming",
    "Muskrat",
    "North American beaver",
    "American mink",
    "American marten",
    "Fisher",
    "River otter"
  ];

  const yellowstoneNationalParkAnimals = [
    "American bison",
    "Elk",
    "Mule deer",
    "Bighorn sheep",
    "Mountain goat",
    "Black bear",
    "Grizzly bear",
    "Gray wolf",
    "Coyote",
    "Red fox",
    "Bobcat",
    "Wolverine",
    "River otter",
    "Beaver",
    "Bald eagle",
    "Golden eagle",
    "Peregrine falcon",
    "Osprey",
    "Great horned owl",
    "Barred owl",
    "Great gray owl",
    "Northern pygmy owl",
    "Boreal owl",
    "Northern saw-whet owl",
    "Common raven",
    "Clark's nutcracker",
    "Yellow-bellied marmot",
    "Golden-mantled ground squirrel",
    "Least chipmunk",
    "Yellow-pine chipmunk",
    "American pika",
    "Northern pocket gopher",
    "Meadow vole",
    "Montane vole",
    "Long-tailed vole",
  ];

  const yosemiteNationalParkAnimals = [
    "Mule deer",
    "Black bear",
    "Coyote",
    "Bobcat",
    "Mountain lion",
    "Gray fox",
    "Ringtail",
    "Striped skunk",
    "American badger",
    "Yellow-bellied marmot",
    "Golden-mantled ground squirrel",
    "California ground squirrel",
    "Least chipmunk",
    "Long-eared chipmunk",
    "Douglas squirrel",
    "Western gray squirrel",
    "Pygmy nuthatch",
    "White-breasted nuthatch",
    "Brown creeper",
    "Bewick's wren",
    "House wren",
    "Pacific wren",
    "Western bluebird",
    "Steller's jay",
    "California scrub jay",
    "Common raven",
    "American robin",
    "Dark-eyed junco",
    "Yellow-rumped warbler",
    "Western tanager",
    "Black-headed grosbeak",
    "Wrentit",
    "California thrasher",
    "Olive-sided flycatcher"
  ];

  const zionNationalParkAnimals = [
    "Mule deer",
    "Desert bighorn sheep",
    "Ringtail cat",
    "Coyote",
    "Bobcat",
    "Mountain lion",
    "Striped skunk",
    "Rock squirrel",
    "White-throated woodrat",
    "Deer mouse",
    "Canyon mouse",
    "Western harvest mouse",
    "California myotis",
    "Western small-footed myotis",
    "Yuma myotis",
    "California leaf-nosed bat",
    "Townsend's big-eared bat",
    "Pallid bat",
    "Western pipistrelle",
    "Common raven",
    "Northern mockingbird",
    "Curve-billed thrasher",
    "Canyon wren",
    "Rock wren",
    "House finch",
    "Black-throated sparrow",
    "Common side-blotched lizard",
    "Greater short-horned lizard",
    "Desert spiny lizard",
    "Chuckwalla",
    "Sidewinder",
    "Gopher snake",
    "Great Basin rattlesnake",
    "Mojave rattlesnake",
    "Colorado River toad"
  ];

  const allWildlife = [
    acadiaAnimals,
    americanSamoaAnimals,
    archesAnimals,
    badlandsAnimals,
    bigBendAnimals,
    biscayneAnimals,
    blackCanyonAnimals,
    bryceCanyonAnimals,
    canyonlandsAnimals,
    capitolReefAnimals,
    carlsbadCavernsAnimals,
    channelIslandsAnimals,
    congareeAnimals,
    craterLakeAnimals,
    cuyahogaValleyAnimals,
    deathValleyAnimals,
    denaliAnimals,
    dryTortugasAnimals,
    evergladesAnimals,
    gatesOfTheArcticAnimals,
    gatewayArchAnimals,
    glacierNationalParkAnimals,
    glacierBayNationalParkAnimals,
    grandCanyonNationalParkAnimals,
    grandTetonNationalParkAnimals,
    greatBasinNationalParkAnimals,
    greatSandDunesNationalParkAnimals,
    greatSmokyMountainsNationalParkAnimals,
    guadalupeMountainsNationalParkAnimals,
    haleakalaNationalParkAnimals,
    hawaiiVolcanoesNationalParkAnimals,
    hotSpringsNationalParkAnimals,
    indianaDunesNationalParkAnimals,
    isleRoyaleNationalParkAnimals,
    joshuaTreeNationalParkAnimals,
    katmaiNationalParkAnimals,
    kenaiFjordsNationalParkAnimals,
    kingsCanyonNationalParkAnimals,
    kobukValleyNationalParkAnimals,
    lakeClarkNationalParkAnimals,
    lassenVolcanicNationalParkAnimals,
    mammothCaveNationalParkAnimals,
    mesaVerdeNationalParkAnimals,
    mountRainierNationalParkAnimals,
    newRiverGorgeNationalParkAnimals,
    northCascadesNationalParkAnimals,
    olympicNationalParkAnimals,
    petrifiedForestNationalParkAnimals,
    pinnaclesNationalParkAnimals,
    redwoodNationalParkAnimals,
    rockyMountainNationalParkAnimals,
    saguaroNationalParkAnimals,
    sequoiaNationalParkAnimals,
    shenandoahNationalParkAnimals,
    theodoreRooseveltNationalParkAnimals,
    virginIslandsNationalParkAnimals,
    voyageursNationalParkAnimals,
    whiteSandsNationalParkAnimals,
    windCaveNationalParkAnimals,
    wrangellStEliasNationalParkAnimals,
    yellowstoneNationalParkAnimals,
    yosemiteNationalParkAnimals,
    zionNationalParkAnimals
  ]

const noDuplicates = []

allWildlife.map(park => {
  park.forEach(animal => {
    if (!noDuplicates.includes(animal))
      noDuplicates.push(animal)
  })
})

// !! -- find me --

const coloradoRiverToad = {
  id: 1,
  name: "Colorado River Toad",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Bufo-alvarius-coloradokr%C3%B6te.jpg/640px-Bufo-alvarius-coloradokr%C3%B6te.jpg",
  fact: "The Colorado River Toad is also known as the Sonoran Desert toad. It secretes a potent venom from its parotoid glands, which contains the psychoactive compound 5-MeO-DMT and bufotenin."
};

const mojaveRattlesnake = {
  id: 2,
  name: "Mojave Rattlesnake",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Crotalus_scutulatus_mesquite_flats_mojave_preserve_california.jpg/640px-Crotalus_scutulatus_mesquite_flats_mojave_preserve_california.jpg",
  fact: "The Mojave rattlesnake is a venomous pit viper species found in the southwestern United States and northwestern Mexico. It is known for its potent neurotoxic venom, which is considered to be one of the most dangerous among North American rattlesnakes."
};

const americanBlackBear = {
  id: 3,
  name: "American Black Bear",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/American_black_bear_2_small.jpg/640px-American_black_bear_2_small.jpg",
  fact: "The American black bear is the smallest and most common bear species in North America. It is an omnivore with a diet that varies depending on the season and availability of food sources."
};

const whiteTailedDeer = {
  id: 4,
  name: "White-Tailed Deer",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Odocoileus_virginianus_head_on.jpg/640px-Odocoileus_virginianus_head_on.jpg",
  fact: "The white-tailed deer is a widespread and adaptable species of deer found throughout North America. It is a herbivore that feeds on a variety of plants, including grasses, leaves, and twigs."
};

const easternCoyote = {
  id: 5,
  name: "Eastern Coyote",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Eastern_coyote_%28Canis_latrans_var._coyotl%29.jpg/640px-Eastern_coyote_%28Canis_latrans_var._coyotl%29.jpg",
  fact: "The eastern coyote is a canid species found in eastern North America. It is a larger and more adaptable coyote than its western counterpart, and its diet includes a wider variety of prey, including small mammals, birds, reptiles, amphibians, and fruits."
};

const redFox = {
  id: 6,
  name: "Red Fox",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Vulpes_vulpes_laying_in_snow.jpg/640px-Vulpes_vulpes_laying_in_snow.jpg",
  fact: "The red fox is a widespread and adaptable species of fox found throughout the Northern Hemisphere. It is an omnivore with a diet that varies depending on the season and availability of food sources, but typically includes small mammals, birds, reptiles, amphibians, insects, and fruits."
};

const snowshoeHare = {
  id: 7,
  name: "Snowshoe Hare",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Snowshoe_Hare.jpg/640px-Snowshoe_Hare.jpg",
  fact: "The snowshoe hare is a large North American hare found in boreal and montane forests. It is named for its large hind feet, which allow it to move easily over snow."
};

const moose = {
  id: 8,
  name: "Moose",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Moose_in_Denali_National_Park.jpg/640px-Moose_in_Denali_National_Park.jpg",
  fact: "The moose is the largest member of the deer family. It is found in boreal and temperate forests of North America, Europe, and Asia."
};

const bobcat = {
  id: 9,
  name: "Bobcat",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Bobcat_standing.jpg/640px-Bobcat_standing.jpg",
  fact: "The bobcat is a medium-sized wild cat native to North America. It is named for its short, bobbed tail, which is black on the tip."
};

const fisher = {
  id: 10,
  name: "Fisher",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Pekania_pennanti_%282%29.jpg/640px-Pekania_pennanti_%282%29.jpg",
  fact: "The fisher is a small, solitary, nocturnal, omnivorous mammal native to North America. It is a member of the weasel family and is closely related to the American marten."
};

const northAmericanRiverOtter = {
  id: 11,
  name: "North American River Otter",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Lontra_canadensis_-_North_American_river_otter_-_head_and_torso.jpg/640px-Lontra_canadensis_-_North_American_river_otter_-_head_and_torso.jpg",
  fact: "The North American river otter is a semiaquatic mammal native to North America. It is the largest member of the weasel family in North America and is found in a variety of habitats, including rivers, lakes, and coastal areas."
};

const americanMink = {
  id: 12,
  name: "American Mink",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Neovison_vison_2.jpg/640px-Neovison_vison_2.jpg",
  fact: "The American mink is a semiaquatic mammal native to North America. It is a member of the weasel family and is closely related to the European mink."
};

const stripedSkunk = {
  id: 13,
  name: "Striped Skunk",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Mephitis_mephitis_%28Striped_Skunk%29.jpg/640px-Mephitis_mephitis_%28Striped_Skunk%29.jpg",
  fact: "The striped skunk is a mammal native to North America. It is known for its ability to spray a foul-smelling liquid from its anal glands as a defense mechanism."
};

const porcupine = {
  id: 14,
  name: "Porcupine",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Erethizon_dorsatum_%28North_American_Porcupine%29.jpg/640px-Erethizon_dorsatum_%28North_American_Porcupine%29.jpg",
  fact: "The porcupine is a rodent with a coat of sharp spines, or quills, that defend against predators. The North American porcupine is the only porcupine species in North America."
};

const easternGraySquirrel = {
  id: 15,
  name: "Eastern Gray Squirrel",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Sciurus_carolinensis.jpg/640px-Sciurus_carolinensis.jpg",
  fact: "The eastern gray squirrel is a tree squirrel native to eastern North America. It is the most common squirrel species in North America and is found in a variety of habitats, including forests, parks, and urban areas."
};

const redSquirrel = {
  id: 16,
  name: "Red Squirrel",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Tamiasciurus_hudsonicus.jpg/640px-Tamiasciurus_hudsonicus.jpg",
  fact: "The red squirrel is a small, reddish-brown squirrel found in North America and Eurasia. It is a common inhabitant of coniferous forests and is known for its loud chattering calls."
};

const americanMarten = {
  id: 17,
  name: "American Marten",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/American_Marten.jpg/640px-American_Marten.jpg",
  fact: "The American marten is a small, slender weasel-like mammal found in North America. It is a skilled climber and is often found in coniferous forests."
};

const meadowVole = {
  id: 18,
  name: "Meadow Vole",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Microtus_pennsylvanicus.jpg/640px-Microtus_pennsylvanicus.jpg",
  fact: "The meadow vole is a small, mouse-like rodent found in North America. It is a common inhabitant of grasslands and meadows and is an important prey species for many predators."
};

const woodchuck = {
  id: 19,
  name: "Woodchuck",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Marmota_monax_2.jpg/640px-Marmota_monax_2.jpg",
  fact: "The woodchuck, also known as the groundhog, is a large, ground-dwelling squirrel found in North America. It is a herbivore and is known for its ability to hibernate during the winter."
};

const northernRaccoon = {
  id: 20,
  name: "Northern Raccoon",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Procyon_lotor_-_Virginia.jpg/640px-Procyon_lotor_-_Virginia.jpg",
  fact: "The northern raccoon is a medium-sized mammal found in North America. It is a nocturnal omnivore and is known for its intelligence and adaptability."
};

const littleBrownBat = {
  id: 21,
  name: "Little Brown Bat",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Myotis_lucifugus.jpg/640px-Myotis_lucifugus.jpg",
  fact: "The little brown bat is a small, insectivorous bat found in North America. It is one of the most common bats in North America and is an important predator of insects."
};

const bigBrownBat = {
  id: 22,
  name: "Big Brown Bat",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Eptesicus_fuscus.jpg/640px-Eptesicus_fuscus.jpg",
  fact: "The big brown bat is a medium-sized, insectivorous bat found in North America. It is one of the largest bats in North America and is an important predator of insects."
};


const baldEagle = {
  id: 23,
  name: "Bald eagle",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Bald_Eagle_Landing_on_Branch.jpg/640px-Bald_Eagle_Landing_on_Branch.jpg",
  fact: "The bald eagle is a majestic bird of prey found in North America. It is the national emblem of the United States and is a symbol of strength and freedom."
};

const peregrineFalcon = {
  id: 24,
  name: "Peregrine falcon",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Falco_peregrinus_-_Barbary_Falcon.jpg/640px-Falco_peregrinus_-_Barbary_Falcon.jpg",
  fact: "The peregrine falcon is the fastest bird in the world, capable of reaching speeds of over 200 miles per hour during its hunting dives."
};

const osprey = {
  id: 25,
  name: "Osprey",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Pandion_haliaetus_-_Osprey.jpg/640px-Pandion_haliaetus_-_Osprey.jpg",
  fact: "The osprey is a fish-eating bird of prey found worldwide. It is also known as the sea hawk or fish hawk, and it is a skilled hunter that dives into water to catch fish."
};

const commonLoon = {
  id: 26,
  name: "Common loon",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Gavia_immer_-_Common_Loon.jpg/640px-Gavia_immer_-_Common_Loon.jpg",
  fact: "The common loon is a large waterbird found in North America and Eurasia. It is known for its haunting calls and its ability to dive deep underwater to catch fish."
};

const blackCappedChickadee = {
  id: 27,
  name: "Black-capped chickadee",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Poecile_atricapillus_001.jpg/640px-Poecile_atricapillus_001.jpg",
  fact: "The black-capped chickadee is a small, non-migratory songbird found in North America. It is known for its cheerful song and its ability to store food for later consumption."
};

const americanRobin = {
  id: 28,
  name: "American robin",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Turdus_migratorius.jpg/640px-Turdus_migratorius.jpg",
  fact: "The American robin is a familiar songbird found in North America. It is known for its red breast and its cheerful song, which is often heard in the early morning."
};

const mourningDove = {
  id: 29,
  name: "Mourning dove",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Zenaida_macroura_004.jpg/640px-Zenaida_macroura_004.jpg",
  fact: "The mourning dove is a common dove found in North America. It is known for its soft, mournful cooing sound and its gentle nature."
};

const blueJay = {
  id: 30,
  name: "Blue jay",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Cyanocitta_cristata_004.jpg/640px-Cyanocitta_cristata_004.jpg",
  fact: "The blue jay is a large, colorful songbird found in North America. It is known for its intelligence, its loud calls, and its aggressive behavior towards other birds."
};

const americanCrow = {
  id: 31,
  name: "American crow",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Corvus_brachyrhynchos_004.jpg/640px-Corvus_brachyrhynchos_004.jpg",
  fact: "The American crow is a large, black bird found in North America. It is known for its intelligence, its ability to mimic sounds, and its social behavior."
};

const commonRaven = {
  id: 32,
  name: "Common raven",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Corvus_corax_-_Rookery_Bay.jpg/640px-Corvus_corax_-_Rookery_Bay.jpg",
  fact: "The common raven is a large, black bird found in North America, Europe, Asia, and North Africa. It is the largest member of the crow family and is known for its intelligence, its ability to mimic sounds, and its playful behavior."
};

const northernCardinal = {
  id: 33,
  name: "Northern cardinal",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Cardinalis_cardinalis_male_4.jpg/640px-Cardinalis_cardinalis_male_4.jpg",
  fact: "The northern cardinal is a medium-sized songbird found in North America. The male is a brilliant red color, while the female is a more muted brown. It is a popular backyard bird and is known for its cheerful song."
};

const americanGoldfinch = {
  id: 34,
  name: "American goldfinch",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Spinus_tristis_-_Smithsonian_NMNH_-_554615.jpg/640px-Spinus_tristis_-_Smithsonian_NMNH_-_554615.jpg",
  fact: "The American goldfinch is a small songbird found in North America. The male is a bright yellow color with black markings, while the female is a more muted yellow-green. It is a popular backyard bird and is known for its acrobatic flight and its cheerful song."
};

const songSparrow = {
  id: 35,
  name: "Song sparrow",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Melospiza_melodia01.jpg/640px-Melospiza_melodia01.jpg",
  fact: "The song sparrow is a small songbird found in North America. It is a common backyard bird and is known for its varied and complex song."
};

const flyingFox = {
  id: 36,
  name: "Flying fox",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Pteropus_conspicillatus_-_flying_fox_-_Kakadu_-_Australia_-_20040525.jpg/640px-Pteropus_conspicillatus_-_flying_fox_-_Kakadu_-_Australia_-_20040525.jpg",
  fact: "The flying fox is a large bat found in tropical and subtropical regions of Asia, Australia, and Africa. It is not a true fox, but is named for its fox-like face. Flying foxes are important pollinators and seed dispersers."
};

const pacificBoa = {
  id: 37,
  name: "Pacific boa",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Candoia_bibroni_-Dresden_Zoo-8a.jpg/454px-Candoia_bibroni_-Dresden_Zoo-8a.jpg",
  fact: "The Pacific boa is a non-venomous snake found in the Pacific Islands. It is a constrictor, meaning that it kills its prey by squeezing it."
};

const coconutCrab = {
  id: 38,
  name: "Coconut crab",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Birgus_latro_on_me.jpg/640px-Birgus_latro_on_me.jpg",
  fact: "The coconut crab is the largest terrestrial arthropod in the world. It is found on islands in the Indian and Pacific Oceans. It is named for its ability to climb coconut trees and open coconuts with its strong claws."
};

const giantCentipede = {
  id: 39,
  name: "Giant centipede",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Scolopendra_gigantea01.jpg/640px-Scolopendra_gigantea01.jpg",
  fact: "The giant centipede is one of the largest centipedes in the world. It can grow up to 12 inches long and has a venomous bite that can be painful to humans."
};

const crownedPigeon = {
  id: 40,
  name: "Crowned pigeon",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Goura_cristata_-_San_Diego_Zoo.jpg/640px-Goura_cristata_-_San_Diego_Zoo.jpg",
  fact: "The crowned pigeon is a large, colorful pigeon found in New Guinea. It is named for its distinctive crest of feathers on its head. It is a popular bird in zoos and aviaries."
};

const purpleCappedFruitDove = {
  id: 41,
  name: "Purple-capped fruit dove",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Ptilinopus_purpuratus_-_Lamington_National_Park%2C_Australia_-_female_-_8_January_2008.jpg/640px-Ptilinopus_purpuratus_-_Lamington_National_Park%2C_Australia_-_female_-_8_January_2008.jpg",
  fact: "The purple-capped fruit dove is a small, colorful dove found in Australia. It is named for its distinctive purple cap of feathers on its head. It is a common bird in rainforests and other wooded areas."
};

const manyColoredFruitDove = {
  id: 42,
  name: "Many-colored fruit dove",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Ptilinopus_varius_at_Auckland_Zoo.jpg/640px-Ptilinopus_varius_at_Auckland_Zoo.jpg",
  fact: "The many-colored fruit dove is a small, colorful dove found in Indonesia and Papua New Guinea. It is named for its brightly colored plumage, which includes green, blue, yellow, and red feathers. It is a common bird in rainforests and other wooded areas."
};

const pacificImperialPigeon = {
  id: 43,
  name: "Pacific imperial pigeon",
  imageLink: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Ducula_pacifica_-_Flickr_-_Lip_Kee.jpg/640px-Ducula_pacifica_-_Flickr_-_Lip_Kee.jpg",
  fact: "The Pacific imperial pigeon is a large, pigeon found in the Pacific Islands. It is named for its large size and its distinctive white breast and belly. It is a common bird in rainforests."
}

const objects = []

export default noDuplicates